### ISSUE TITLE
Administration compoment helper issue

### ISSUE THREAD

**Issue by lukas-marek** [jodit/jodit-joomla#2]
Hello
I've found an issue in the new version 3.1.8

File: administrator/components/com_jodit
Line 24: require_once JPATH_COMPONENT_ADMINISTRATOR . '/helpers/jodit.php';

The required file does not exist.

**Comment by PierreCorell** [comment]
this issue I have seen, too and fixxed with https://github.com/jodit/jodit-joomla/pull/3
